### ISSUE TITLE
Mlflow MinIO settings  

### ISSUE THREAD

**Issue by MateusHenriqueOliveira** [larribas/helm-charts#10]
Hello everyone, 
I'm trying to deploy Mlflow helm-chart using postgresql as backEndStore and Minio as defaultArtifactRoot but the pod gives a crashloopback

My config

```
postgres:
     username: postgres
     password: postgres
     host: postgresql.database.svc.cluster.local
     port: 5433
     database: mlflow

# defaultArtifactRoot -- A local or remote filepath (e.g. s3://my-bucket). It is mandatory when specifying a database backend store
defaultArtifactRoot: 
  minio:
    url: minio.deepstorage.svc.cluster.local:9000
    accesskey: minio
    secretkey: minio123
    bucket: mlflow
```

Can someone help me out, see what I'm doing wrong or send me samples of this time of configuration.
Thanks in advance!
